### ISSUE TITLE
Priorities

### ISSUE THREAD

**Issue by bclinkinbeard** [CenterForAssessment/NCIEA_Internship_2015#1]
Hey @dbetebenner @cdepascale @ganders309 @lcancado, I'm wondering what I can do to be most helpful to you in the near term. Since I last saw you I've been researching ways to share D3 code (there are no well established standards), resources for learning Git and GitHub, and experimenting with Atom plugin development to improve the workflow of creating and updating Gists directly from the editor.

What I'd like to know is which of those things you would like to see progress in first. (Or if you would rather see something else entirely.)

If you'd prefer to have some D3 charts to work with, what kind would be most helpful? Can that question even be answered before you choose topics?

**Comment by dbetebenner** [comment]
Hi Ben,

I thought the plan was to fully document our approach in the README.md this week on GitHub based upon what we decided last week.

Damian Betebenner

**Comment by bclinkinbeard** [comment]
Yea, I'm working on that now, but since it's all still pretty high level I'm starting to think about where to dive deeper. I'm researching and assembling the best links and resources so the documentation isn't just the list I jotted down while we reviewed the pieces last week. :)
- Step 0 - Install Git, SourceTree, and Atom or Visual Studio Code
- Step 1 - Find and fork a template gist
- Step 2 - Make tweaks to the code
- Step 3 - Publish new version of the Gist
- Step 4 - Get bl.ocks.org link for the new Gist

I guess maybe a better way to frame my priorities question is what part of that documentation would you like to see fleshed out and expanded first? More help understanding the primary tools and concepts we're using (step 0), more resources and guidance for tweaking a baseline Gist (step 2), or better tools for the publishing process (steps 3 and 4)?

**Comment by bclinkinbeard** [comment]
OK, the Getting Started section of the README is in pretty good shape now as I have documented each step of the process with images. The next two sections are _Working with the code_ and _Publishing your changes_, both of which are pretty basic right now.

I'm kind of thinking it would make sense for me to start building our own custom Atom plugin. I think we could easily make the starting of a local server and the publishing of changes a push button operation, making Terminal and SourceTree completely unnecessary for basic workflows.

Thoughts?

**Comment by dbetebenner** [comment]
I think that makes sense. How long do you think that will take?

Damian Betebenner
Center for Assessment
31 Mount Vernon Streetx-apple-data-detectors://3
Dover, NH 03820x-apple-data-detectors://3

857-234-2474tel:857-234-2474 (cell)
603-516-7900tel:603-516-7900 (office)
603-516-7910tel:603-516-7910 (fax)

dbetebenner@nciea.orgmailto:dbetebenner@nciea.org
@DBetebenner

Sent from my iPhone

On Jun 10, 2015, at 2:54 PM, Ben Clinkinbeard <notifications@github.com<mailto:notifications@github.com>> wrote:

OK, the Getting Started section of the README is in pretty good shape now as I have documented each step of the process with images. The next two sections are Working with the code and Publishing your changes, both of which are pretty basic right now.

I'm kind of thinking it would make sense for me to start building our own custom Atom plugin. I think we could easily make the starting of a local server and the publishing of changes a push button operation, making Terminal and SourceTree completely unnecessary for basic workflows.

Thoughts?

##

**Comment by bclinkinbeard** [comment]
It's hard to say since I am new to Atom plugin dev. I just got a very crude, non-interactive version working that commits all changes with a generic message and pushes the changes. My best guess is I could have something usable by about Wednesday of next week, since I am out the rest of this week.
