### ISSUE TITLE
Gist viewer is up and running!

### ISSUE THREAD

**Issue by bclinkinbeard** [CenterForAssessment/NCIEA_Internship_2015#3]
https://nciea-gist-viewer.herokuapp.com/06a2cc498a33d5144d70/

Change the Gist id on the end to view any available gist! This is a basic implementation in about 50 lines of code. Currently, it assumes there is an index.html and just shows the output, like the /raw URLs on bl.ocks.org.

@dbetebenner can we touch base this afternoon or tomorrow to plot out next features?

**Comment by dbetebenner** [comment]
Awesome!

Damian Betebenner
Center for Assessment
31 Mount Vernon Street
Dover, NH 03820

857-234-2474 (cell)
603-516-7900 (office)
603-516-7910 (fax)

dbetebenner@nciea.orgmailto:dbetebenner@nciea.org
@DBetebenner

On Jun 18, 2015, at 11:19 AM, Ben Clinkinbeard <notifications@github.com<mailto:notifications@github.com>> wrote:

https://nciea-gist-viewer.herokuapp.com/06a2cc498a33d5144d70/

Change the Gist id on the end to view any available gist! This is a basic implementation in about 50 lines of code. Currently, it assumes there is an index.html and just shows the output, like the /raw URLs on bl.ocks.orghttp://bl.ocks.org.

@dbetebennerhttps://github.com/dbetebenner can we touch base this afternoon or tomorrow to plot out next features?

**Comment by bclinkinbeard** [comment]
I just pushed some edits that add a small info panel in the bottom left corner linking to the Gist itself and the author's Gists page. The changes were deployed to Heroku automatically when I pushed to GitHub. :)

**Comment by bclinkinbeard** [comment]
Initial Markdown support is now in. http://nciea-gist-viewer.herokuapp.com/bdba0145af07d5afeb92/

Basically, the viewer will include any CSS and JS files in the Gist, and the Markdown content is converted and inserted into the body of the page. If you need to reference a hosted library like D3 you can put that script tag in the index.md like the example linked above, but most everything else should happen in individual files.
